services:
  rest_api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SPEAKERS_PATH=/app/data/speakers
    volumes:
      - ./data/speakers:/app/data/speakers
    networks:
      - voiceprint

  web_ui:
    build:
      context: web_ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - rest_api
    networks:
      - voiceprint

networks:
  voiceprint:
    driver: bridge

volumes:
  speakers_data:
