services:
  http_server:
    container_name: voiceprint_http_server
    image: voiceprint_http_server
    build: ./voiceprint
    ports:
      - "5000:5000"
    volumes:
      - ./voiceprint/voices:/app/voices
      - ./voiceprint/models:/app/models
    user: "1000:1000"
